#!/usr/bin/env bash
# Combine the shared rule files into a single CLAUDE.md and install it globally.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$REPO_DIR/common"
DEST="${CLAUDE_HOME:-$HOME/.claude}/CLAUDE.md"

# Files to include, in order. NASA-flight-software.md is deliberately excluded.
SOURCES=(
  "writing.md"
  "coding-rules.md"
)

for f in "${SOURCES[@]}"; do
  if [[ ! -f "$SRC_DIR/$f" ]]; then
    echo "sync.sh: missing source file: $SRC_DIR/$f" >&2
    exit 1
  fi
done

mkdir -p "$(dirname "$DEST")"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "<!-- Generated by sync.sh from $SRC_DIR. Edit the sources, not this file. -->"
  echo
  for i in "${!SOURCES[@]}"; do
    (( i > 0 )) && echo && echo "---" && echo
    cat "$SRC_DIR/${SOURCES[$i]}"
  done
} > "$tmp"

if [[ -f "$DEST" ]] && cmp -s "$tmp" "$DEST"; then
  echo "sync.sh: $DEST already up to date"
  exit 0
fi

if [[ -f "$DEST" ]]; then
  cp "$DEST" "$DEST.bak"
  echo "sync.sh: previous CLAUDE.md backed up to $DEST.bak"
fi

cp "$tmp" "$DEST"
echo "sync.sh: wrote $DEST ($(wc -l < "$DEST" | tr -d ' ') lines from ${#SOURCES[@]} files)"
